-- Add new columns to kyc_verifications table for detailed KYC data
ALTER TABLE public.kyc_verifications
ADD COLUMN IF NOT EXISTS msisdn text,
ADD COLUMN IF NOT EXISTS country text,
ADD COLUMN IF NOT EXISTS country_abbreviation text,
ADD COLUMN IF NOT EXISTS full_name text,
ADD COLUMN IF NOT EXISTS first_name text,
ADD COLUMN IF NOT EXISTS surname text,
ADD COLUMN IF NOT EXISTS date_of_birth date,
ADD COLUMN IF NOT EXISTS sex text,
ADD COLUMN IF NOT EXISTS document_number text,
ADD COLUMN IF NOT EXISTS physical_address text,
ADD COLUMN IF NOT EXISTS postal_address text,
ADD COLUMN IF NOT EXISTS date_of_issue date,
ADD COLUMN IF NOT EXISTS expiry_date date,
ADD COLUMN IF NOT EXISTS add_phone_number_1 text,
ADD COLUMN IF NOT EXISTS add_phone_number_2 text,
ADD COLUMN IF NOT EXISTS add_phone_number_3 text,
ADD COLUMN IF NOT EXISTS add_phone_number_4 text,
ADD COLUMN IF NOT EXISTS add_phone_number_5 text,
ADD COLUMN IF NOT EXISTS add_phone_number_6 text,
ADD COLUMN IF NOT EXISTS add_phone_number_7 text,
ADD COLUMN IF NOT EXISTS add_phone_number_8 text,
ADD COLUMN IF NOT EXISTS add_phone_number_9 text,
ADD COLUMN IF NOT EXISTS add_phone_number_10 text;